spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    s